"""judge decisions

Revision ID: 9d7abba51cf5
Revises: c76e5501ada6
Create Date: 2026-09-27 03:19:05.661863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d7abba51cf5"
down_revision: str | Sequence[str] | None = "c76e5501ada6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judge_decisions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("vacancy_hash", sa.String(length=64), nullable=False),
        sa.Column("failure", sa.String(length=32), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("discarded", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_judge_decisions_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judge_decisions")),
    )
    op.create_index(
        "ix_judge_decisions_attempt",
        "judge_decisions",
        ["match_id", "profile_version", "prompt_version", "vacancy_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_judge_decisions_decided_at"), "judge_decisions", ["decided_at"], unique=False
    )
    op.create_index(
        "uq_judge_decisions_success",
        "judge_decisions",
        ["match_id", "profile_version", "prompt_version", "vacancy_hash"],
        unique=True,
        postgresql_where=sa.text("failure IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_judge_decisions_success",
        table_name="judge_decisions",
        postgresql_where=sa.text("failure IS NULL"),
    )
    op.drop_index(op.f("ix_judge_decisions_decided_at"), table_name="judge_decisions")
    op.drop_index("ix_judge_decisions_attempt", table_name="judge_decisions")
    op.drop_table("judge_decisions")
    # ### end Alembic commands ###
