"""multi-user schema

Revision ID: c76e5501ada6
Revises: 848ead290d74
Create Date: 2026-09-26 20:47:39.425661

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c76e5501ada6"
down_revision: str | Sequence[str] | None = "848ead290d74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("monthly_budget_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_candidate_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profiles")),
        sa.UniqueConstraint(
            "user_id", "version", name=op.f("uq_candidate_profiles_user_id_version")
        ),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vacancy_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score_value", sa.Integer(), nullable=True),
        sa.Column("scored_count", sa.Integer(), nullable=True),
        sa.Column("unknown_count", sa.Integer(), nullable=True),
        sa.Column("profile_version", sa.Integer(), nullable=True),
        sa.Column("blocked_by", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_matches_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("fk_matches_vacancy_id_vacancies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint("user_id", "vacancy_id", name=op.f("uq_matches_user_id_vacancy_id")),
    )
    op.create_index("ix_matches_user_id_status", "matches", ["user_id", "status"], unique=False)
    op.create_index(op.f("ix_matches_vacancy_id"), "matches", ["vacancy_id"], unique=False)
    op.create_table(
        "match_status_changes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=False),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_status_changes_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_status_changes")),
    )
    op.create_index(
        op.f("ix_match_status_changes_match_id"), "match_status_changes", ["match_id"], unique=False
    )
    # Destructive on purpose: old statuses and their history have no user to belong to,
    # and the database holds no real data yet. With real data this would be an
    # expand/contract migration that copies statuses into matches before dropping them.
    op.drop_index(op.f("ix_vacancy_status_changes_vacancy_id"), table_name="vacancy_status_changes")
    op.drop_table("vacancy_status_changes")
    op.drop_index(op.f("ix_vacancies_status"), table_name="vacancies")
    op.drop_column("vacancies", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The default fills rows that already exist; it is removed right away so the schema
    # matches revision 848ead290d74 exactly.
    op.add_column(
        "vacancies",
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
            server_default="new",
        ),
    )
    op.alter_column("vacancies", "status", server_default=None)
    op.create_index(op.f("ix_vacancies_status"), "vacancies", ["status"], unique=False)
    op.create_table(
        "vacancy_status_changes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("vacancy_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("from_status", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("to_status", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "changed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("fk_vacancy_status_changes_vacancy_id_vacancies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy_status_changes")),
    )
    op.create_index(
        op.f("ix_vacancy_status_changes_vacancy_id"),
        "vacancy_status_changes",
        ["vacancy_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_match_status_changes_match_id"), table_name="match_status_changes")
    op.drop_table("match_status_changes")
    op.drop_index(op.f("ix_matches_vacancy_id"), table_name="matches")
    op.drop_index("ix_matches_user_id_status", table_name="matches")
    op.drop_table("matches")
    op.drop_table("candidate_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
